// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZUCWDC1rOZv6jK9gN0yu2Ig3GfmFTzs',
    appId: '1:640237132976:web:3847aa1886269a693cef75',
    messagingSenderId: '640237132976',
    projectId: 'singspeaktech',
    authDomain: 'singspeaktech.firebaseapp.com',
    storageBucket: 'singspeaktech.firebasestorage.app',
    measurementId: 'G-094DP0C9RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbqs2zgab21Cr2t_J9EEQlCVQ1d8qwWw',
    appId: '1:640237132976:android:c156aae432e4bd013cef75',
    messagingSenderId: '640237132976',
    projectId: 'singspeaktech',
    storageBucket: 'singspeaktech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyssmU02JLX8yJe5vsJBMVFu8S4mkZTVw',
    appId: '1:640237132976:ios:203bdd7342bc29a83cef75',
    messagingSenderId: '640237132976',
    projectId: 'singspeaktech',
    storageBucket: 'singspeaktech.firebasestorage.app',
    androidClientId: '640237132976-aosufii07c2em2i0rpvj36kj1bcoq9mf.apps.googleusercontent.com',
    iosClientId: '640237132976-sckd44re7j1anabsdi65781m2vnucjb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.singSpeakTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyssmU02JLX8yJe5vsJBMVFu8S4mkZTVw',
    appId: '1:640237132976:ios:203bdd7342bc29a83cef75',
    messagingSenderId: '640237132976',
    projectId: 'singspeaktech',
    storageBucket: 'singspeaktech.firebasestorage.app',
    androidClientId: '640237132976-aosufii07c2em2i0rpvj36kj1bcoq9mf.apps.googleusercontent.com',
    iosClientId: '640237132976-sckd44re7j1anabsdi65781m2vnucjb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.singSpeakTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZUCWDC1rOZv6jK9gN0yu2Ig3GfmFTzs',
    appId: '1:640237132976:web:6315e67355a302be3cef75',
    messagingSenderId: '640237132976',
    projectId: 'singspeaktech',
    authDomain: 'singspeaktech.firebaseapp.com',
    storageBucket: 'singspeaktech.firebasestorage.app',
    measurementId: 'G-7EX3HBRJFH',
  );

}